### ISSUE TITLE
Isoquant results to AllInfo file

### ISSUE THREAD

**Issue by biozhangzhou** [noush-joglekar/biccn_tilgner_scisorseq#1]
Hello,

I didn't find the codes for processing the isoquant results into the extended annotation file and the AllInfo file. Can you share it with me?

Zhou

**Comment by noush-joglekar** [comment]
Hi Zhou, 

The extended annotation file was made by just collating the lines containing "nic" i.e., "novel in catalog" transcripts from the "transcript_models.gtf" file onto the gencode annotation. 

Converting the isoquant output to the all-info format can be done using the function "correctedBed2AllInfo" in [scisorseqr](https://github.com/noush-joglekar/scisorseqr). 
See `?scisorseqr::correctedBed2AllInfo` for help

**Comment by biozhangzhou** [comment]
Thanks for the quick response.
